/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hryt_iov_speech_cppnative_Sdk */

#ifndef _Included_com_hryt_iov_speech_cppnative_Sdk
#define _Included_com_hryt_iov_speech_cppnative_Sdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hryt_iov_speech_cppnative_Sdk
 * Method:    nativeDownload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hryt_iov_speech_cppnative_Sdk_nativeDownload
  (JNIEnv * , jobject);

#ifdef __cplusplus
}
#endif
#endif
